addons:
  code_climate:
    repo_token: 5a67e1ff1682c417c946f7ff805da320a3a62885a02563498038b885cfbebcdc
services:
  - mongodb
language: node_js
node_js:
  - "0.11"
script: "npm run-script test-travis"
notifications:
  slack: deserthacks:FzYUGKFMXlcLd825hnI6YiYt
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
