language: node_js
node_js:
  - "0.11"
script: "npm run-script test-travis"
notifications:
  slack: deserthacks:FzYUGKFMXlcLd825hnI6YiYt
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"